--- linux-2.6.32.bak/arch/x86/mm/Makefile	2009-12-03 11:51:21.000000000 +0800
+++ linux-2.6.32/arch/x86/mm/Makefile	2014-03-24 16:21:59.122145093 +0800
@@ -16,6 +16,7 @@ obj-$(CONFIG_X86_PTDUMP)	+= dump_pagetab
 obj-$(CONFIG_HIGHMEM)		+= highmem_32.o
 
 obj-$(CONFIG_KMEMCHECK)		+= kmemcheck/
+obj-y		+= modulememcheck/
 
 obj-$(CONFIG_MMIOTRACE)		+= mmiotrace.o
 mmiotrace-y			:= kmmio.o pf_in.o mmio-mod.o
